version: '3'

services:
    app: 
        build: .
        image: kokt0203/goapi
    production:
        image: kokt0203/goapi:${BUILD_NUMBER}
        volumes: 
            - .:/code
        entrypoint: /main
        ports: 
            - "4030:4040"